add tags option
wieni/wmsubscription_mailchimp pull request #3
Opened 2021-04-28 10:51 UTC by Taravde

## Description

### Documentation

## Related Issues

2021-04-28 13:26 UTC, DieterHolvoet commented
Die tags is iets Mailchimp-specifiek, ik zou daar dus geen aanpassing voor doen in `wmsubscription`. Wat ge kunt doen is in [`Subscriber`](https://github.com/wieni/wmsubscription_mailchimp/blob/master/src/Subscriber.php) een property + getter/setter/evt. adder toevoegen en dat dan uitlezen in `addSubscriber`, zo blijft Mailchimp-specifieke functionaliteit uit de abstracte interface.

2021-05-03 14:08 UTC, Taravde commented
Aangepast

2021-05-03 15:23 UTC, DieterHolvoet requested changes

2021-05-03 15:23 UTC, DieterHolvoet commented on src/Plugin/SubscriptionTool/Mailchimp.php
> +    ){
Deze aanpassing moet niet

2021-05-03 15:23 UTC, DieterHolvoet commented on src/Plugin/SubscriptionTool/Mailchimp.php
> +        if (!empty($tags = $payload->getTags())) {
Maak maar dit van, is cleaner:
```php
if ($tags = $payload->getTags()) {
```

2021-05-03 15:23 UTC, DieterHolvoet commented on src/Plugin/SubscriptionTool/Mailchimp.php
> +    public function isUpdatable(ListInterface $list, PayloadInterface $payload): bool
Waarom zijn `isUpdatable` en `validateArguments` van plaats veranderd? `public` methodes komen altijd voor `protected`, dus pas maar terug aan.

2021-05-03 15:23 UTC, DieterHolvoet commented on src/Subscriber.php
> +    /** @var array */
Duidelijker als je hier zegt wat voor een array het is, bv.
```php
/** @var string[] */
```

2021-05-03 19:36 UTC, Taravde commented
aangepast

2021-05-04 08:05 UTC, merged